<?xml version="1.0"?>
<package format="2">
  <name>joy_to_helm</name>
  <version>0.0.0</version>
  <description>The joy_to_helm package</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>

  <depend>rclpy</depend>
  <depend>marine_interfaces</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>joy</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
