# List of TaskInformations to use with task management
# service calls

# The task id list (may be empty)
string[]                               task_ids
---
# The list of tasks resulting from the service call
marine_nav_interfaces/TaskInformation[]   tasks
