# List of TaskInformations to use with task management
# service calls

# The task id list (may be empty)
string[]                               task_ids
---
# The list of tasks resulting from the service call
project11_nav_msgs/TaskInformation[]   tasks
