<?xml version="1.0"?>
<package format="2">
  <name>command_bridge</name>
  <version>0.0.0</version>
  <description>The command_bridge package</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
