<?xml version="1.0"?>
<package format="2">
  <name>mission_manager</name>
  <version>0.0.0</version>
  <description>The mission_manager package</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>
  <license>BSD-3-Clause</license>

  <depend>geometry_msgs</depend>
  <depend>marine_nav_interfaces</depend>
  <depend>marine_nav_tasks</depend>
  <depend>mission_manager_interfaces</depend>
  <depend>nav_msgs</depend>
  <depend>marine_autonomy</depend>
  <depend>marine_interfaces</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
    <rosdoc2>rosdoc2.yaml</rosdoc2>
  </export>
</package>
