udp_bridge:
  ros__parameters:
    name: robot
    remotes:
      operator:
        connections:
          default:
            port: 4200
            maximumBytesPerSecond: 1000000
            topics:
              platforms: {source: /marine/platforms}
              nav_orientation: {source: marine/nav/orientation}
              nav_position: {source: marine/nav/position}
              nav_velocity: {source: marine/nav/velocity}
              nav_active_sensor: {source: marine/nav/active_sensor}
              marine_display: {source: marine/display}
              marine_heartbeat: {source: marine/heartbeat}
              marine_status_mission_manager: {source: marine/status/mission_manager}
              marine_response: {source: marine/response}
              # diagnostics: {source: /diagnostics}
              tf: {source: /tf}
              tf_static: {source: /tf_static}
              control_helm: {source: marine/control/helm}
              odom: {source: odom}
              nav_visualization_markers: {source: navigator/visualization_markers}

helm_manager:
  ros__parameters:
    piloting_modes:
      active: ['manual', 'autonomous']
      standby: ['standby']
