name: docker-jazzy-ros-core

on:
  push:
    branches: [ jazzy ]
  pull_request:
    branches: [ jazzy ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    container:
      image: ros:jazzy-ros-core

    steps:
    - name: Update apt
      run: apt update
    - name: Install ros dev tools
      run: DEBIAN_FRONTEND=noninteractive apt -y install ros-dev-tools
    - name: Checkout Project11
      uses: actions/checkout@v3
    - name: Init rosdep
      run: rosdep init
    - name: Update rosdep
      run: rosdep update
    - name: Create workspace
      run: mkdir -p ../jazzy_ws/src
    - name: Install repos
      run: vcs import --input config/repos/simulation.repos ../jazzy_ws/src/
    - name: Install ROS dependencies
      working-directory: ../jazzy_ws/
      run: DEBIAN_FRONTEND=noninteractive rosdep install --from-paths src --ignore-src -r -y
    - name: Colcon build
      working-directory: ../jazzy_ws/
      run: bash -c 'source /opt/ros/jazzy/setup.bash && colcon build'
