name: docker-jazzy-ros-core

on:
  push:
    branches: [ jazzy ]
  pull_request:
    branches: [ jazzy ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    container:
      image: ros:jazzy-ros-core

    steps:
    - name: Update apt
      run: apt update
    - name: Install ros dev tools
      run: DEBIAN_FRONTEND=noninteractive apt -y install ros-dev-tools
    - name: Checkout Project11
      uses: actions/checkout@v3
    - name: Init rosdep
      run: rosdep init
    - name: Update rosdep
      run: rosdep update
    - name: Create workspace
      run: mkdir -p ../jazzy_ws/src
    - name: Install repos
      run: |
        vcs import --input config/repos/underlay.repos ../jazzy_ws/src/
        vcs import --input config/repos/core.repos ../jazzy_ws/src/
    - name: Replace checked-out unh_marine_autonomy with PR branch
      run: |
        rm -rf ../jazzy_ws/src/unh_marine_autonomy
        ln -s $GITHUB_WORKSPACE ../jazzy_ws/src/unh_marine_autonomy
    - name: Install ROS dependencies
      working-directory: ../jazzy_ws/
      run: DEBIAN_FRONTEND=noninteractive rosdep install --from-paths src --ignore-src -r -y
    - name: Colcon build
      working-directory: ../jazzy_ws/
      run: bash -c 'source /opt/ros/jazzy/setup.bash && colcon build --packages-up-to helm_manager command_bridge mission_manager joy_to_helm marine_autonomy'
    - name: Colcon test
      working-directory: ../jazzy_ws/
      run: bash -c 'source /opt/ros/jazzy/setup.bash && colcon test --packages-select marine_interfaces marine_autonomy helm_manager joy_to_helm command_bridge mission_manager mission_manager_interfaces --event-handlers console_direct+ --return-code-on-test-failure'
    - name: Test results
      working-directory: ../jazzy_ws/
      run: bash -c 'source /opt/ros/jazzy/setup.bash && colcon test-result --verbose --packages-select marine_interfaces marine_autonomy helm_manager joy_to_helm command_bridge mission_manager mission_manager_interfaces'
      if: always()
